config/routes.rb
Rails.application.routes.draw do
  resources :consultors
  resources :posts
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/consultor.rb
class Consultor < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/consultors_controller.rb
class ConsultorsController < ApplicationController
  before_action :set_consultor, only: [:show, :edit, :update, :destroy]

  # GET /consultors
  # GET /consultors.json
  def index
    @consultors = Consultor.all
    respond_to do |format|
      format.html
      format.json
      format.pdf { render template: 'consultors/reporte_consultores', pdf: 'reporte',layout: 'pdf.html'}
    end
  end

  # GET /consultors/1
  # GET /consultors/1.json
  def show
  end

  # GET /consultors/new
  def new
    @consultor = Consultor.new
  end

  # GET /consultors/1/edit
  def edit
  end

  # POST /consultors
  # POST /consultors.json
  def create
    @consultor = Consultor.new(consultor_params)

    respond_to do |format|
      if @consultor.save
        format.html { redirect_to @consultor, notice: 'Consultor was successfully created.' }
        format.json { render :show, status: :created, location: @consultor }
      else
        format.html { render :new }
        format.json { render json: @consultor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consultors/1
  # PATCH/PUT /consultors/1.json
  def update
    respond_to do |format|
      if @consultor.update(consultor_params)
        format.html { redirect_to @consultor, notice: 'Consultor was successfully updated.' }
        format.json { render :show, status: :ok, location: @consultor }
      else
        format.html { render :edit }
        format.json { render json: @consultor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consultors/1
  # DELETE /consultors/1.json
  def destroy
    @consultor.destroy
    respond_to do |format|
      format.html { redirect_to consultors_url, notice: 'Consultor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consultor
      @consultor = Consultor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def consultor_params
      params.require(:consultor).permit(:nombre, :apellido, :edad, :direccion, :telefono)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:titulo, :contenido, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:nombre, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consultors_helper.rb
module ConsultorsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/consultors/_form.html.erb
<%= form_with(model: consultor, local: true) do |form| %>
  <% if consultor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(consultor.errors.count, "error") %> prohibited this consultor from being saved:</h2>

      <ul>
      <% consultor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :apellido %>
    <%= form.text_field :apellido %>
  </div>

  <div class="field">
    <%= form.label :edad %>
    <%= form.number_field :edad %>
  </div>

  <div class="field">
    <%= form.label :direccion %>
    <%= form.text_field :direccion %>
  </div>

  <div class="field">
    <%= form.label :telefono %>
    <%= form.number_field :telefono %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/consultors/edit.html.erb
<h1>Editing Consultor</h1>

<%= render 'form', consultor: @consultor %>

<%= link_to 'Show', @consultor %> |
<%= link_to 'Back', consultors_path %>

app/views/consultors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Consultors</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Edad</th>
      <th>Direccion</th>
      <th>Telefono</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @consultors.each do |consultor| %>
      <tr>
        <td><%= consultor.nombre %></td>
        <td><%= consultor.apellido %></td>
        <td><%= consultor.edad %></td>
        <td><%= consultor.direccion %></td>
        <td><%= consultor.telefono %></td>
        <td><%= link_to 'Show', consultor %></td>
        <td><%= link_to 'Edit', edit_consultor_path(consultor) %></td>
        <td><%= link_to 'Destroy', consultor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Consultor', new_consultor_path %>

app/views/consultors/new.html.erb
<h1>New Consultor</h1>

<%= render 'form', consultor: @consultor %>

<%= link_to 'Back', consultors_path %>

app/views/consultors/reporte_consultores.pdf.erb
<h1>reporte de consultores</h1>
    <table class="table">
    <thead>
    <tr>
     <th style=" width:200px ">nombre</th>
     <th style="width:200px">apellido</th>
    <tr>
    </thead>
    <tbody>
      <% @consultors.each do |consultors| %>

        <tr>
        <td> <%= consultors.nombre %> </td>
        <td> <%= consultors.apellido%></td>
        <tr>
          <% end %>
    </tbody>
    </table>

app/views/consultors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @consultor.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @consultor.apellido %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @consultor.edad %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @consultor.direccion %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @consultor.telefono %>
</p>

<%= link_to 'Edit', edit_consultor_path(@consultor) %> |
<%= link_to 'Back', consultors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rrhh2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <%= wicked_pdf_stylesheet_link_tag 'pdf' %>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="utf-8">
</head>
<body>
<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :contenido %>
    <%= form.text_field :contenido %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Contenido</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.titulo %></td>
        <td><%= post.contenido %></td>
        <td><%= post.user_id %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @post.titulo %>
</p>

<p>
  <strong>Contenido:</strong>
  <%= @post.contenido %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.nombre %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @user.nombre %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>